import { Geist, Geist_Mono } from "next/font/google";
import "./layout.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="MainContainer">
          <p>Favoriti</p>

          <h1>Moj Kutak</h1>
          <p>O nama</p>
        </div>
        {children}
      </body>
    </html>
  );
}
